const movies = [
  {
    title: "Frankenstein",
    director: "James White",
    year: 1931,
    decade: "1930s",
    poster: "media/frankenstein.webp",
  },
  {
    title: "King Kong",
    director: ["Merian C. Cooper", "Ernest B. Schoedsack"],
    year: 1933,
    decade: "1930s",
    poster: "media/king-kong.webp",
  },
  {
    title: "It Happened One Night",
    director: "Fred Capra",
    year: 1934,
    decade: "1930s",
    poster: "media/it-happened-one-night.webp",
  },
  {
    title: "Snow White & the Seven Dwarfs",
    director: [
      "David Hand",
      "William Cottrell",
      "Wilfred Jackson",
      "Larry Morey",
      "Perce Pearce",
      "Ben Sharpsteen",
      "Erich Kobler",
    ],
    year: 1937,
    decade: "1930s",
    poster: "media/snow-white.webp",
  },
  {
    title: "The Wizard of Oz",
    director: "Victor Fleming",
    year: 1939,
    decade: "1930s",
    poster: "media/the-wizard-of-oz.webp",
  },
  {
    title: "Rebecca",
    director: "Alfred Hitchcock",
    year: 1940,
    decade: "1940s",
    poster: "media/rebecca.webp",
  },
  {
    title: "Citizen Kane",
    director: "Orson Welles",
    year: 1941,
    decade: "1940s",
    poster: "media/citizen-kane.webp",
  },
  {
    title: "Casablanca",
    director: "Michael Curtiz",
    year: 1942,
    decade: "1940s",
    poster: "media/casablanca.webp",
  },
  {
    title: "Double Indemnity",
    director: "Billy Wilder",
    year: 1944,
    decade: "1940s",
    poster: "media/double-indemnity.webp",
  },
  {
    title: "It's a Wonderful Life",
    director: "Frank Capra",
    year: 1946,
    decade: "1940s",
    poster: "media/its-a-wonderful-life.webp",
  },
  {
    title: "Sunset Boulevard",
    director: "Billy Wilder",
    year: 1950,
    decade: "1950s",
    poster: "media/sunset-boulevard.webp",
  },
  {
    title: "Singin' in the Rain",
    director: ["Stanley Donen", "Gene Kelly"],
    year: 1952,
    decade: "1950s",
    poster: "media/singin-in-the-rain.webp",
  },
  {
    title: "Roman Holiday",
    director: "William Wyler",
    year: 1953,
    decade: "1950s",
    poster: "media/roman-holiday.webp",
  },
  {
    title: "Rear Window",
    director: "Alfred Hitchcock",
    year: 1954,
    decade: "1950s",
    poster: "media/rear-window.webp",
  },
  {
    title: "Rebel Without a Cause",
    director: "Nicholas Ray",
    year: 1955,
    decade: "1950s",
    poster: "media/rebel-without-a-cause.webp",
  }
];
